---

- name: elasticsearch container
  docker:
    name: "elasticsearch"
    image: "elasticsearch:5"
    pull: always
    volumes: "{{elasticsearch_directory }}:/usr/share/elasticsearch"
    command: elasticsearch
    state: started
    log_driver: journald
    restart_policy: always
    docker_api_version: "1.23"
    net: "host"
    pid: "host"
    ports: "{{ elasticsearch_global_config.http_port }}, 9300"
