---

- name: elasticsearch container
  docker:
    name: "elasticsearch"
    image: "elasticsearch:{{ elasticsearch_version }}"
    pull: always
    privileged: true
    volumes:
      - "{{elasticsearch_directory_config }}:/usr/share/elasticsearch/config"
      - "{{elasticsearch_directory_data }}:/usr/share/elasticsearch/data"
      - "{{elasticsearch_directory_logs }}:/usr/share/elasticsearch/logs"
      - "{{elasticsearch_directory_plugins }}:/usr/share/elasticsearch/plugins"
    command: elasticsearch
    state: started
    restart_policy: always
    docker_api_version: "1.23"
    net: "host"
    pid: "host"
    ports: "{{ elasticsearch_global_config['http.port'] }}, 9300"
